service: Serverless-event-booking-platform

frameworkVersion: '3'

# Provider
provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  profile: Moheed

# Functions
functions:
  # Event Planner Flow

  # Get One Event Planner
  getEventPlanner:
    handler: functions/event_planner/getOneEventPlanner.getEventPlanner
    events:
      - http:
          path: /get-one-event-planner
          method: GET
          cors: true
          authorizer:
              name: CognitoAuthorizer
              type: COGNITO_USER_POOLS
              arn: !GetAtt CognitoUserPool.Arn
    
    # IAM Role Statements
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:GetItem
        Resource:
          - arn:aws:dynamodb:us-east-1:654654320621:table/moheedEventPlanner
    
    # Environment Variables 
    environment:
      event_planner_table: moheedEventPlanner

  # Update Event Planner using by userId 
  updateEvent:
    handler: functions/event_planner/editEventPlannerUser.eventPlannerUser
    events:
      - http:
          path: /edit-event-planner
          method: PUT
          cors: true
          authorizer:
              name: CognitoAuthorizer
              type: COGNITO_USER_POOLS
              arn: !GetAtt CognitoUserPool.Arn

    # IAM Role Statements
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
        Resource:
          - arn:aws:dynamodb:us-east-1:654654320621:table/moheedEventPlanner
    
    # Environment Variables 
    environment:
      event_planner_table: moheedEventPlanner

  # Post Confirmation Flow
  postFunc:
    handler: trigger/postConfirmation.postConfirmationTrigger
    events:
      - cognitoUserPool:
          pool: us-east-1_Gdlj8Z0v6
          trigger: PostConfirmation

    # IAM Role Statements
    iamRoleStatements:
      - Effect: Allow
        Action: 
          - cognito-idp:AdminAddUserToGroup
          - cognito-idp:AmazonCognitoPowerUser
          - dynamodb:PutItem
        Resource:
          - arn:aws:cognito-idp:us-east-1:654654320621:userpool/us-east-1_Gdlj8Z0v6
          - arn:aws:dynamodb:us-east-1:654654320621:table/moheedTicketPurchaser
          - arn:aws:dynamodb:us-east-1:654654320621:table/moheedEventPlanner
    
    # Environment Variables 
    environment:
      event_planner_table: moheedEventPlanner
      event_group_name: eventPlanner
      user_ticket_purchaser_table: moheedTicketPurchaser
      group_name: userTicketPurchaser

  # Events Flow with CRUD Operation

  # Create Event
  createEventData:
    handler: functions/event_data/createEvent.addEvents
    events:
      - http:
          path: /create-event
          method: POST
          cors: true
          authorizer:
              name: CognitoAuthorizer
              type: COGNITO_USER_POOLS
              arn: !GetAtt CognitoUserPool.Arn

    # IAM Role Statements
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource:
          - arn:aws:dynamodb:us-east-1:654654320621:table/eventPlannerData
    
    # Environment Variables
    environment:
      events_table_name: eventPlannerData

  # Get Event using by GSI
  getEventData:
    handler: functions/event_data/getOneEvent.getEvent
    events:
      - http:
          path: /get-event
          method: GET
          cors: true
          authorizer:
              name: CognitoAuthorizer
              type: COGNITO_USER_POOLS
              arn: !GetAtt CognitoUserPool.Arn

    # IAM Role Statements
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
          - dynamodb:Scan
        Resource:
          - arn:aws:dynamodb:us-east-1:654654320621:table/eventPlannerData
          - arn:aws:dynamodb:us-east-1:654654320621:table/eventPlannerData/index/event-planner-index
    
    # Environment Variables
    environment:
      events_table_name: eventPlannerData
      index_name: event-planner-index

  # Update Event using by eventId
  updateEventData:
    handler: functions/event_data/updateEvent.editEventPlanner
    events:
      - http:
          path: /edit-event/{eventId}
          method: PUT
          cors: true
          authorizer:
              name: CognitoAuthorizer
              type: COGNITO_USER_POOLS
              arn: !GetAtt CognitoUserPool.Arn

    # IAM Role Statements
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
        Resource:
          - arn:aws:dynamodb:us-east-1:654654320621:table/eventPlannerData
    
    # Environment Variables
    environment:
      events_table_name: eventPlannerData

  # Delete Event using by eventId
  deleteEventData:
    handler: functions/event_data/deleteEvent.deleteEventItem
    events:
      - http:
          path: /delete-event/{eventId}
          method: DELETE
          cors: true
          authorizer:
              name: CognitoAuthorizer
              type: COGNITO_USER_POOLS
              arn: !GetAtt CognitoUserPool.Arn

    # IAM Role Statements
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:DeleteItem
        Resource:
          - arn:aws:dynamodb:us-east-1:654654320621:table/eventPlannerData
    
    # Environment Variables
    environment:
      events_table_name: eventPlannerData
  
  # Booking Ticket System Flow

  # Update booking ticket
  createBooking:
    handler: functions/booking_system/booking_seat.bookTickets
    events:
      - http:
          path: /create-bookingTicket
          method: POST
          cors: true
          authorizer:
              name: CognitoAuthorizer
              type: COGNITO_USER_POOLS
              arn: !GetAtt CognitoUserPool.Arn

    # IAM Role Statements
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource:
          - arn:aws:dynamodb:us-east-1:654654320621:table/bookingTicketSystem
    
    # Environment Variables
    environment:
      tickets_table_name: bookingTicketSystem

# Resources
resources:
  Resources:

    # Create DynamoDB Table for Event Planner
    EventPlannerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: moheedEventPlanner
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

    # Create DynamoDB Table for User Ticket Buyer
    UserTicketPurchaser:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: moheedTicketPurchaser
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

    # Create DynamoDB Table for Event Data
    EventsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: eventPlannerData
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: eventId
            AttributeType: S
          - AttributeName: eventPlannerId
            AttributeType: S
        KeySchema:
          - AttributeName: eventId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: event-planner-index
            KeySchema:
              - AttributeName: eventPlannerId
                KeyType: HASH
            Projection:
              ProjectionType: ALL

    # Create DynamoDB Table for Booking Ticket
    BookingTicket:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: bookingTicketSystem
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: ticketId
            AttributeType: S
        KeySchema:
          - AttributeName: ticketId
            KeyType: HASH

    # Create Cognito User Pool
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        AutoVerifiedAttributes:
          - email
        UsernameAttributes:
          - email
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireUppercase: true
            RequireLowercase: true
            RequireNumbers: true
            RequireSymbols: true
        Schema:
          - AttributeDataType: String
            Name: email
            Mutable: true
            Required: true
          - AttributeDataType: String
            Name: given_name
            Mutable: true
            Required: true
          - AttributeDataType: String
            Name: family_name
            Mutable: true
            Required: true
          
    #  Create Cognito Client
    WebCognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: client
        UserPoolId: !Ref CognitoUserPool
        ExplicitAuthFlows:
          - ALLOW_USER_SRP_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH

    # Event Planner Group
    EventPlannerGroup:
      Type: AWS::Cognito::UserPoolGroup
      Properties:
        GroupName: "eventPlanner"
        UserPoolId: !Ref CognitoUserPool

    # User Ticket Buyer Group
    UserTicketPurchaserGroup:
      Type: AWS::Cognito::UserPoolGroup
      Properties:
        GroupName: "userTicketPurchaser"
        UserPoolId: !Ref CognitoUserPool

# Plugins
plugins:
  - serverless-export-env
  - serverless-iam-roles-per-function