service: Serverless-event-booking-platform

frameworkVersion: '3'

# Provider
provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  profile: Moheed

# Functions
functions:
  # Event Planner Flow

  # Add Event Data Lambda Function
  addNewEvent:
    handler: functions/event_planner/createEventPlanner.addEventPlanner
    events:
      - http:
          path: /newevent
          method: POST
          cors: true
    
    # IAM Role Statements
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource:
          - arn:aws:dynamodb:us-east-1:654654320621:table/eventData
    
    # Environment Variables 
    environment:
      event_data_table: eventData
  
  # Update Event Data Lambda Function
  editEvent:
    handler: functions/event_planner/updateEventPlanner.editEventPlanner
    events:
      - http:
          path: /editevent/{id}
          method: PUT
          cors: true
    
    # IAM Role Statements
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
        Resource:
          - arn:aws:dynamodb:us-east-1:654654320621:table/eventData
    
    # Environment Variables 
    environment:
      event_data_table: eventData

  # Delete Event Data Lambda Function
  deleteEvent:
    handler: functions/event_planner/deleteEventPlanner.removeEventPlanner
    events:
      - http:
          path: /deleteevent/{id}
          method: DELETE
          cors: true
    
    # IAM Role Statements
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:DeleteItem
        Resource:
          - arn:aws:dynamodb:us-east-1:654654320621:table/eventData
    
    # Environment Variables 
    environment:
      event_data_table: eventData

  # List of All Event Data Lambda Function
  listAllEvents:
    handler: functions/event_planner/getEventPlanner.getAllEventPlanner
    events:
      - http:
          path: /allevents
          method: GET
          cors: true
    
    # IAM Role Statements
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:ScanItem
        Resource:
          - arn:aws:dynamodb:us-east-1:654654320621:table/eventData
    
    # Environment Variables 
    environment:
      event_data_table: eventData

  # Post Confirmation Flow
  postFunc:
    handler: src/trigger/postConfirmation.postConfirmationTrigger
    events:
      - cognitoUserPool:
          pool: us-east-1_SIvc79Ld9
          trigger: PostConfirmation

    # IAM Role Statements
    iamRoleStatements:
      - Effect: Allow
        Action: 
          - cognito-idp:AdminAddUserToGroup
          - cognito-idp:AmazonCognitoPowerUser
          - dynamodb:PutItem
        Resource:
          - arn:aws:cognito-idp:us-east-1:654654320621:userpool/us-east-1_SIvc79Ld9
          - arn:aws:dynamodb:us-east-1:654654320621:table/moheedTicketPurchaser
          - arn:aws:dynamodb:us-east-1:654654320621:table/moheedEventPlanner
    
    # Environment Variables 
    environment:
      event_planner_table: moheedEventPlanner
      event_group_name: eventPlanner
      user_ticket_purchaser_table: moheedTicketPurchaser
      group_name: userTicketPurchaser

  # User Ticket Purchase Flow

  # Add Event Data Lambda Function
  addEventBooking:
    handler: functions/user_ticket_purchase/createEventBooking.addEventBooking
    events:
      - http:
          path: /neweventbooking
          method: POST
          cors: true
    
    # IAM Role Statements
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource:
          - arn:aws:dynamodb:us-east-1:654654320621:table/bookingSystem
    
    # Environment Variables 
    environment:
      event_booking_table: bookingSystem
  
  # Update Event Data Lambda Function
  editEventBooking:
    handler: functions/user_ticket_purchase/updateEventBooking.updateEventBookings
    events:
      - http:
          path: /editeventbooking/{id}
          method: PUT
          cors: true
    
    # IAM Role Statements
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
        Resource:
          - arn:aws:dynamodb:us-east-1:654654320621:table/bookingSystem
    
    # Environment Variables 
    environment:
      event_booking_table: bookingSystem

  # Delete Event Data Lambda Function
  eventBooking:
    handler: functions/user_ticket_purchase/deleteEventBooking.removeEventBooking
    events:
      - http:
          path: /deleteeventbooking/{id}
          method: DELETE
          cors: true
    
    # IAM Role Statements
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:DeleteItem
        Resource:
          - arn:aws:dynamodb:us-east-1:654654320621:table/bookingSystem
    
    # Environment Variables 
    environment:
      event_booking_table: bookingSystem

  # List of All Event Data Lambda Function
  allEventBooking:
    handler: functions/user_ticket_purchase/getEventBookings.getAllEventBookings
    events:
      - http:
          path: /alleventbookings
          method: GET
          cors: true
    
    # IAM Role Statements
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:ScanItem
        Resource:
          - arn:aws:dynamodb:us-east-1:654654320621:table/bookingSystem
    
    # Environment Variables 
    environment:
      event_booking_table: bookingSystem

# Resources
resources:
  Resources:

    # Create DynamoDB for EventPlanner
    EventPlannerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: moheedEventPlanner
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

    # Create DynamoDB for UserTicketPurchaser
    UserTicketPurchaser:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: moheedTicketPurchaser
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

    # Create DynamoDB for Event Data
    EventData:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: eventData
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    
    # Create DynamoDB for Booking System
    BookingTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: bookingSystem
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

    # Create DynamoDB for Booking
    eventBookingTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: eventBooking
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

    # Create Cognito User Pool
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        AutoVerifiedAttributes:
          - email
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireUppercase: true
            RequireLowercase: true
            RequireNumbers: true
            RequireSymbols: true
        Schema:
          - AttributeDataType: String
            DeveloperOnlyAttribute: true
            Mutable: true
            Name: profile
            NumberAttributeConstraints:
              MaxValue: '25'
              MinValue: '0'
            Required: false
            StringAttributeConstraints:
              MaxLength: '55'
              MinLength: '0'
          - AttributeDataType: String
            Name: email
            Mutable: true
            Required: true
          - AttributeDataType: String
            Name: given_name
            Mutable: true
            Required: true
          - AttributeDataType: String
            Name: family_name
            Mutable: true
            Required: true
          
    #  Create Cognito Web
    WebCognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: client
        UserPoolId: !Ref CognitoUserPool
        ExplicitAuthFlows:
          - ALLOW_USER_SRP_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
    
    #  Create Cognito Server
    ServerCognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: server
        UserPoolId: !Ref CognitoUserPool
        ExplicitAuthFlows:
          - ALLOW_ADMIN_USER_PASSWORD_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH

    # Event Planner Group
    EventPlannerGroup:
      Type: AWS::Cognito::UserPoolGroup
      Properties:
        GroupName: "eventPlanner"
        UserPoolId: !Ref CognitoUserPool

    # User Ticket Purchaser Group
    UserTicketPurchaserGroup:
      Type: AWS::Cognito::UserPoolGroup
      Properties:
        GroupName: "userTicketPurchaser"
        UserPoolId: !Ref CognitoUserPool

# Plugins
plugins:
  - serverless-export-env
  - serverless-iam-roles-per-function