service: Serverless-event-booking-platform

frameworkVersion: '3'

# Provider
provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  profile: Moheed

  # IAM Role Statements
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:654654320621:table/moheedEventPlanner
        - arn:aws:dynamodb:us-east-1:654654320621:table/moheedTicketPurchaser
    - Effect: Allow
      Action: 
        - cognito-idp:AdminAddUserToGroup
      Resource: '*'

  # Environment Variables 
  environment:
    event_planner_table: moheedEventPlanner
    event_group_name: eventPlanner
    user_ticket_purchaser_table: moheedTicketPurchaser
    group_name: userTicketPurchaser

# Functions
functions:

  # Event Planner Flow
  addNewEvent:
    handler: functions/event_planner/create.createEventPlanner
    events:
      - http:
          path: /newevent
          method: POST
          cors: true
  editEvent:
    handler: functions/event_planner/update.updateEventPlanner
    events:
      - http:
          path: /editevent/{id}
          method: PUT
          cors: true
  deleteEvent:
    handler: functions/event_planner/delete.deleteEventPlanner
    events:
      - http:
          path: /deleteevent/{id}
          method: DELETE
          cors: true
  listAllEvents:
    handler: functions/event_planner/list.getEventPlanner
    events:
      - http:
          path: /allevents
          method: GET
          cors: true

  # Post Confirmation Flow
  postFunc:
    handler: src/trigger/postConfirmation.postConfirmationTrigger
    events:
      - cognitoUserPool:
          pool: us-east-1_SIvc79Ld9
          trigger: PostConfirmation
    iamRoleStatements:
      - Effect: Allow
        Action: 
          # - lambda:
          - cognito-idp:PostConfirmation
        Resource:
          - arn:aws:lambda:us-east-1:654654320621:function:Serverless-event-booking-platform-dev-postFunc
          - arn:aws:cognito-idp:us-east-1:654654320621:userpool/us-east-1_SIvc79Ld9

# Resources
resources:
  Resources:

    # Create DynamoDB for EventPlanner
    EventPlannerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: moheedEventPlanner
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

    # Create DynamoDB for UserTicketPurchaser
    UserTicketPurchaser:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: moheedTicketPurchaser
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

    # Create DynamoDB for Event Data
    EventData:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: eventData
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    
    # Create DynamoDB for Booking System
    BookingTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: bookingSystem
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

    # Create Cognito User Pool
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        AutoVerifiedAttributes:
          - email
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireUppercase: true
            RequireLowercase: true
            RequireNumbers: true
            RequireSymbols: true
        Schema:
          - AttributeDataType: String
            DeveloperOnlyAttribute: true
            Mutable: true
            Name: profile
            NumberAttributeConstraints:
              MaxValue: '25'
              MinValue: '0'
            Required: false
            StringAttributeConstraints:
              MaxLength: '55'
              MinLength: '0'
          - AttributeDataType: String
            Name: email
            Mutable: true
            Required: true
          - AttributeDataType: String
            Name: given_name
            Mutable: true
            Required: true
          - AttributeDataType: String
            Name: family_name
            Mutable: true
            Required: true
          
    #  Create Cognito Web
    WebCognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: client
        UserPoolId: !Ref CognitoUserPool
        ExplicitAuthFlows:
          - ALLOW_USER_SRP_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
    
    #  Create Cognito Server
    ServerCognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: server
        UserPoolId: !Ref CognitoUserPool
        ExplicitAuthFlows:
          - ALLOW_ADMIN_USER_PASSWORD_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH

    # Event Planner Group
    EventPlannerGroup:
      Type: AWS::Cognito::UserPoolGroup
      Properties:
        GroupName: "eventPlanner"
        UserPoolId: !Ref CognitoUserPool

    # User Ticket Purchaser Group
    UserTicketPurchaserGroup:
      Type: AWS::Cognito::UserPoolGroup
      Properties:
        GroupName: "userTicketPurchaser"
        UserPoolId: !Ref CognitoUserPool

# Plugins
plugins:
  - serverless-export-env
  - serverless-iam-roles-per-function